server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  cloud:
    gateway:
      routes:
        - id: friends
          uri: http://localhost:8011/
          predicates:
            - Path=/users/me/friends/**, /users/me/blacklist/**
        - id: users
          uri: http://localhost:8010/
          predicates:
            - Path=/users/**, /signin, /signup
