server:
  port: 8010
  error:
    include-stacktrace: never

logging:
  level:
    # Уровень логирования
    ru.greenpix.messenger: ${LOGGING_LEVEL:info}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10100}/${DB_NAME:messenger-user}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}

springdoc:
  swagger-ui:
    path: /swagger

# Настройки безопасности по JWT и API-KEY
security:
  jwt:
    secret: ${JWT_SECRET:VGhpcyBpcyB0ZXN0IHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbg==}
    expiration-minutes: ${JWT_EXPIRATION:1440}
  api:
    key: ${API_KEY:vRY80yTw6FttK16HFPi9rpkIvTN4HgNb}

# URL к интеграционным запросам другим микросервисов
integration:
  friends-service-url: ${FRIENDS_SERVICE_URL:http://localhost:8011}
  file-storage-service-url: ${FRIENDS_SERVICE_URL:http://localhost:8014}

amqp:
  producer:
    notification:
      # Название топика для уведомлений
      topic: ${RABBITMQ_TOPIC:notification-topic}
    user-changes:
      # Название топика для изменений в микросервисе пользователей
      topic: ${RABBITMQ_TOPIC:user-changes-topic}

# Локализация текста уведомлений
notification:
  login: "В Ваш аккаунт был выполнен вход."