version: '3.3'

services:
  postgres-users:
    image: postgres:latest
    ports:
      - "10100:5432"
    environment:
      POSTGRES_DB: messenger-user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgres-friends:
    image: postgres:latest
    ports:
      - "10101:5432"
    environment:
      POSTGRES_DB: messenger-friends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgres-chats:
    image: postgres:latest
    ports:
      - "10102:5432"
    environment:
      POSTGRES_DB: messenger-chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgres-notifications:
    image: postgres:latest
    ports:
      - "10103:5432"
    environment:
      POSTGRES_DB: messenger-notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgres-file-storage:
    image: postgres:latest
    ports:
      - "10104:5432"
    environment:
      POSTGRES_DB: messenger-file-storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  minio:
    image: bitnami/minio:2023.5.18
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin
    volumes:
      - minio-data:/data
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  minio-data: