server:
  port: 8013
  error:
    include-stacktrace: never

logging:
  level:
    ru.greenpix.messenger: ${LOGGING_LEVEL:info}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10103}/${DB_NAME:messenger-notifications}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  rabbitmq:
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}

springdoc:
  swagger-ui:
    path: /swagger

security:
  jwt:
    secret: ${JWT_SECRET:VGhpcyBpcyB0ZXN0IHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbg==}
    expiration-minutes: ${JWT_EXPIRATION:1440}
  api:
    key: ${API_KEY:vRY80yTw6FttK16HFPi9rpkIvTN4HgNb}