version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "10104:5432"
    environment:
      POSTGRES_DB: messenger-file-storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  minio:
    image: bitnami/minio:2023.5.18
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin
    volumes:
      - minio-data:/data

volumes:
  minio-data: