version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "10104:5432"
    environment:
      POSTGRES_DB: messenger-file-storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres