spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger-auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger

security:
  password-encoder: bcrypt