version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "10103:5432"
    environment:
      POSTGRES_DB: messenger-notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq