version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "10103:5432"
    environment:
      POSTGRES_DB: messenger-notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres