server:
  port: 8011
  error:
    # Не включаем stacktrace в http ответ ошибки
    include-stacktrace: never

logging:
  level:
    # Уровень логирования
    ru.greenpix.messenger: ${LOGGING_LEVEL:info}

spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:8MB}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10101}/${DB_NAME:messenger-friends}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
  cloud:
    stream:
      bindings:
        userChangesConsumer-in-0:
          destination: ${RABBITMQ_TOPIC:user-changes-topic}

springdoc:
  swagger-ui:
    path: /swagger

# Настройки безопасности по JWT и API-KEY
security:
  jwt:
    secret: ${JWT_SECRET:VGhpcyBpcyB0ZXN0IHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbg==}
    expiration-minutes: ${JWT_EXPIRATION:1440}
  api:
    key: ${API_KEY:vRY80yTw6FttK16HFPi9rpkIvTN4HgNb}

# URL к интеграционным запросам другим микросервисов
integration:
  users-service-url: ${USERS_SERVICE_URL:http://localhost:8010}

amqp:
  producer:
    # Название топика для уведомлений
    notification:
      topic: ${RABBITMQ_TOPIC:notification-topic}

# Локализация текста уведомлений
notification:
  add-friend: "У Вас новый друг!"
  remove-friend: "С Вами больше не хочет дружить пользователь!"
  block: "Пользователь добавил Вас в черный список!"
  unblock: "Пользователь убрал Вас из черного списка!"