# Этот Docker Compose предназначен для разработки.
# Нужен для того, чтобы локально поднимать окружение.

version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "10100:5432"
    environment:
      POSTGRES_DB: messenger-user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres